### ISSUE TITLE
Request scope objects are acting like singleton .Net core

### ISSUE THREAD

**Issue by jyothi530** [gautema/CQRSlite#50] opened 2017-09-17 19:02 UTC
When a new command is raised for each request, (e.g: CreateInventory request) commandhandler's corresponding dependent objects like DbContext, Repository are not being created newly even if they are registered in request scope using .Net core DI container. They are acting like singleton objects. For the first request they are getting created and for subsequent requests if they are being used outside the scope of handler like in controller methods they are getting created for each request but when it comes to the handler dependent objects are not being created newly and using the objects that are created when the first time handler is created.

**Comment by gautema** [comment] 2017-09-18 07:58
Hi. I'm having problems recreating your issue. I have tried debugging through the sample app to see if I can reproduce your issue there, but I come up short. Can you give some more info, a test or a sample on this issue? What version are you using?

**Comment by gautema** [comment] 2017-09-18 10:04
I found the issue. It looks like the problem is Scoped dependencies don't work since the service locator is used from a singleton context. I'll try to find a solution, but for now, use Transient or Singleton for dependencies of the handlers.

**Comment by gautema** [comment] 2017-09-20 17:37
I checked in some code to show of how this can be solved.

**Closed by gautema** 2017-09-20 17:37 UTC
